
package webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://Source/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "changeParameters", targetNamespace = "http://Source/", className = "webservice.ChangeParameters")
    @ResponseWrapper(localName = "changeParametersResponse", targetNamespace = "http://Source/", className = "webservice.ChangeParametersResponse")
    @Action(input = "http://Source/Server/changeParametersRequest", output = "http://Source/Server/changeParametersResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Source/Server/changeParameters/Fault/Exception")
    })
    public void changeParameters(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://Source/", className = "webservice.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://Source/", className = "webservice.GetStatusResponse")
    @Action(input = "http://Source/Server/getStatusRequest", output = "http://Source/Server/getStatusResponse")
    public int getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addAuto", targetNamespace = "http://Source/", className = "webservice.AddAuto")
    @ResponseWrapper(localName = "addAutoResponse", targetNamespace = "http://Source/", className = "webservice.AddAutoResponse")
    @Action(input = "http://Source/Server/addAutoRequest", output = "http://Source/Server/addAutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Source/Server/addAuto/Fault/Exception")
    })
    public int addAuto(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        long arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderAuto", targetNamespace = "http://Source/", className = "webservice.OrderAuto")
    @ResponseWrapper(localName = "orderAutoResponse", targetNamespace = "http://Source/", className = "webservice.OrderAutoResponse")
    @Action(input = "http://Source/Server/orderAutoRequest", output = "http://Source/Server/orderAutoResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Source/Server/orderAuto/Fault/Exception")
    })
    public double orderAuto(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://Source/", className = "webservice.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://Source/", className = "webservice.SayHelloResponse")
    @Action(input = "http://Source/Server/sayHelloRequest", output = "http://Source/Server/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<webservice.Auto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListFromModel", targetNamespace = "http://Source/", className = "webservice.GetListFromModel")
    @ResponseWrapper(localName = "getListFromModelResponse", targetNamespace = "http://Source/", className = "webservice.GetListFromModelResponse")
    @Action(input = "http://Source/Server/getListFromModelRequest", output = "http://Source/Server/getListFromModelResponse")
    public List<Auto> getListFromModel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "autoReturn", targetNamespace = "http://Source/", className = "webservice.AutoReturn")
    @ResponseWrapper(localName = "autoReturnResponse", targetNamespace = "http://Source/", className = "webservice.AutoReturnResponse")
    @Action(input = "http://Source/Server/autoReturnRequest", output = "http://Source/Server/autoReturnResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://Source/Server/autoReturn/Fault/Exception")
    })
    public void autoReturn(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<webservice.Auto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getList", targetNamespace = "http://Source/", className = "webservice.GetList")
    @ResponseWrapper(localName = "getListResponse", targetNamespace = "http://Source/", className = "webservice.GetListResponse")
    @Action(input = "http://Source/Server/getListRequest", output = "http://Source/Server/getListResponse")
    public List<Auto> getList();

}
